import type { SupplierAttributes, SupplierChannel } from '../types';

/**
 * 配線確認用のサンプル市場（★実在の商品・実在の価格ではありません）。
 *
 * ここは「仕入先の商品」と「Amazon側の商品」を1つの概念(concept)から作る。
 * こうすることで、鍵が1本も無い状態でも
 *   仕入先商品 → Amazon候補検索 → 画像/属性照合 → MATCH SCORE → 採算
 * という流れが実際に最後まで動くことを確認できる。
 *
 * KEEPA_API_KEY と仕入先APIを入れた瞬間に、このファイルは使われなくなる。
 */

export interface SampleConcept {
  key: string;
  /** 仕入先側 */
  supplier: {
    supplier: string;
    channel: SupplierChannel;
    source: string;
    title: string;
    brand?: string | null;
    modelNumber?: string | null;
    gtin?: string | null;
    currency: 'CNY' | 'USD' | 'JPY';
    unitPrice: number;
    moq: number;
    domesticShippingJpy: number;
    intlShippingPerUnitJpy: number;
    dutyRate: number;
    inspectionFeeJpy: number;
    otherImportFeeJpy: number;
    leadTimeDays: number;
    supplierRating: number;
    supplierOrderCount: number;
    attributes: SupplierAttributes;
    /** 同シリーズ（15番の類似探索で展開される別サイズ・別色） */
    variants?: {
      suffix: string;
      title: string;
      unitPrice: number;
      attributes: SupplierAttributes;
    }[];
  };
  /** Amazon側。null なら「Amazonに無い＝照合不成立」を再現する */
  amazon: null | {
    asin: string;
    title: string;
    brand?: string | null;
    modelNumber?: string | null;
    gtin?: string | null;
    category: string;
    priceJpy: number;
    bsr: number;
    reviewCount: number;
    rating: number;
    sellerCount: number;
    isAmazonSelling: boolean;
    monthlySold?: number | null;
    imageCount: number;
    hasVideo: boolean;
    hasAplus: boolean;
    isFood?: boolean;
    temperature?: 'ambient' | 'chilled' | 'frozen';
    attributes: SupplierAttributes;
    /** 画像がどれくらい似ているか（0=同一 / 大きいほど別物）。ビット反転数 */
    imageBitFlips: number;
    /** 価格の振れ幅（価格安定性の採点用） */
    priceVolatility: number;
  };
  /** Amazon側にだけ現れる「別物だが名前が似ている」おとり候補 */
  decoy?: {
    asin: string;
    title: string;
    priceJpy: number;
    bsr: number;
    reviewCount: number;
    rating: number;
    sellerCount: number;
    attributes: SupplierAttributes;
    imageBitFlips: number;
  };
}

// ---- 決定的な擬似ハッシュ生成（サンプル専用）------------------------
// 実データでは jimp が画像を読んで本物の pHash を作る。
// サンプルでは「同じ商品なら近いハッシュ」を再現するためにここで作る。

function seededBits(seed: string): boolean[] {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619) >>> 0;
  }
  const bits: boolean[] = [];
  for (let i = 0; i < 64; i++) {
    h ^= h << 13;
    h >>>= 0;
    h ^= h >> 17;
    h ^= h << 5;
    h >>>= 0;
    bits.push((h & 1) === 1);
  }
  return bits;
}

function bitsToHex(bits: boolean[]): string {
  let out = '';
  for (let i = 0; i < 64; i += 4) {
    let nibble = 0;
    for (let j = 0; j < 4; j++) if (bits[i + j]) nibble |= 1 << (3 - j);
    out += nibble.toString(16);
  }
  return out;
}

/** concept から擬似 pHash を作る。flips が大きいほど「別の画像」になる */
export function sampleImageHash(conceptKey: string, flips = 0): string {
  const bits = seededBits(conceptKey);
  if (flips > 0) {
    const order = seededBits(`${conceptKey}#flip`);
    let flipped = 0;
    for (let i = 0; i < 64 && flipped < flips; i++) {
      const idx = (i * 7 + (order[i] ? 3 : 11)) % 64;
      bits[idx] = !bits[idx];
      flipped++;
    }
  }
  return bitsToHex(bits);
}

const A = (o: SupplierAttributes) => o;

export const SAMPLE_CONCEPTS: SampleConcept[] = [
  // ---------- 高評価になるはずの「地味だが儲かる」帯 ----------
  {
    key: 'drain-cover',
    supplier: {
      supplier: '深圳日用品工場A',
      channel: 'alibaba',
      source: '1688',
      title: '硅胶 地漏盖 防臭 排水口カバー 2枚入 直径11cm グレー',
      brand: null,
      modelNumber: 'DC-110G',
      gtin: null,
      currency: 'CNY',
      unitPrice: 6.2,
      moq: 10,
      domesticShippingJpy: 30,
      intlShippingPerUnitJpy: 95,
      dutyRate: 0.03,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 25,
      leadTimeDays: 14,
      supplierRating: 4.8,
      supplierOrderCount: 3200,
      attributes: A({
        sizeCm: { length: 11, width: 11, height: 1.2 },
        weightG: 90,
        color: 'グレー',
        material: 'シリコン',
        capacity: null,
        setCount: 2,
        spec: '直径11cm 防臭 排水口カバー',
      }),
      variants: [
        { suffix: 'wh', title: '硅胶 地漏盖 防臭 排水口カバー 2枚入 直径11cm ホワイト', unitPrice: 6.2, attributes: A({ color: 'ホワイト', setCount: 2, material: 'シリコン', sizeCm: { length: 11, width: 11, height: 1.2 }, weightG: 90 }) },
        { suffix: '4p', title: '硅胶 地漏盖 防臭 排水口カバー 4枚入 直径11cm グレー', unitPrice: 11.4, attributes: A({ color: 'グレー', setCount: 4, material: 'シリコン', sizeCm: { length: 11, width: 11, height: 2.2 }, weightG: 180 }) },
      ],
    },
    amazon: {
      asin: 'B0SAMPLE001',
      title: '排水口カバー シリコン 防臭 2枚組 直径11cm グレー os-cover',
      brand: 'KURASHIPLUS',
      modelNumber: 'DC-110G',
      gtin: null,
      category: 'ホーム＆キッチン',
      priceJpy: 1280,
      bsr: 8200,
      reviewCount: 41,
      rating: 4.2,
      sellerCount: 3,
      isAmazonSelling: false,
      monthlySold: null,
      imageCount: 4,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 11, width: 11, height: 1.2 },
        weightG: 95,
        color: 'グレー',
        material: 'シリコン',
        setCount: 2,
        spec: '防臭 排水口カバー',
      }),
      imageBitFlips: 2,
      priceVolatility: 0.05,
    },
  },
  {
    key: 'pet-brush',
    supplier: {
      supplier: '義烏ペット用品商社',
      channel: 'alibaba',
      source: '1688',
      title: '宠物梳 抜け毛取りブラシ 犬猫兼用 ステンレス刃 幅9cm ブルー',
      modelNumber: 'PB-90B',
      currency: 'CNY',
      unitPrice: 9.8,
      moq: 20,
      domesticShippingJpy: 25,
      intlShippingPerUnitJpy: 120,
      dutyRate: 0.03,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 25,
      leadTimeDays: 16,
      supplierRating: 4.6,
      supplierOrderCount: 1800,
      attributes: A({
        sizeCm: { length: 18, width: 9, height: 5 },
        weightG: 160,
        color: 'ブルー',
        material: 'ステンレス・ABS',
        setCount: 1,
        spec: '犬猫兼用 抜け毛取り 幅9cm',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE002',
      title: 'ペット ブラシ 抜け毛取り 犬 猫 兼用 ステンレス 幅9cm ブルー',
      brand: 'MOFUCARE',
      modelNumber: 'PB-90B',
      category: 'ペット用品',
      priceJpy: 1780,
      bsr: 4100,
      reviewCount: 128,
      rating: 4.0,
      sellerCount: 6,
      isAmazonSelling: false,
      monthlySold: 210,
      imageCount: 6,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 18, width: 9, height: 5 },
        weightG: 165,
        color: 'ブルー',
        material: 'ステンレス',
        setCount: 1,
        spec: '犬猫兼用 抜け毛取り',
      }),
      imageBitFlips: 3,
      priceVolatility: 0.08,
    },
    decoy: {
      asin: 'B0SAMPLE902',
      title: 'ペット ブラシ 抜け毛取り 犬 猫 兼用 シリコン 手袋タイプ',
      priceJpy: 1180,
      bsr: 22000,
      reviewCount: 33,
      rating: 3.7,
      sellerCount: 11,
      attributes: A({ color: 'ピンク', material: 'シリコン', setCount: 2, spec: '手袋タイプ' }),
      imageBitFlips: 26,
    },
  },
  {
    key: 'car-holder',
    supplier: {
      supplier: '東莞車載用品工場',
      channel: 'alibaba',
      source: 'alibaba',
      title: '车载手机支架 磁吸 マグネット式 スマホホルダー 車載 エアコン吹出口 ブラック',
      modelNumber: 'CH-M2',
      currency: 'CNY',
      unitPrice: 11.5,
      moq: 10,
      domesticShippingJpy: 30,
      intlShippingPerUnitJpy: 110,
      dutyRate: 0.03,
      inspectionFeeJpy: 25,
      otherImportFeeJpy: 25,
      leadTimeDays: 18,
      supplierRating: 4.9,
      supplierOrderCount: 5400,
      attributes: A({
        sizeCm: { length: 8, width: 6, height: 4 },
        weightG: 85,
        color: 'ブラック',
        material: 'アルミ合金',
        setCount: 1,
        spec: 'マグネット式 エアコン吹出口 車載',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE003',
      title: '車載ホルダー マグネット スマホホルダー 車 エアコン吹き出し口 アルミ ブラック',
      brand: 'DRIVEMATE',
      modelNumber: 'CH-M2',
      category: 'カー用品',
      priceJpy: 2480,
      bsr: 2600,
      reviewCount: 76,
      rating: 4.3,
      sellerCount: 5,
      isAmazonSelling: false,
      monthlySold: 340,
      imageCount: 5,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 8, width: 6, height: 4 },
        weightG: 88,
        color: 'ブラック',
        material: 'アルミ',
        setCount: 1,
        spec: 'マグネット 車載 吹き出し口',
      }),
      imageBitFlips: 1,
      priceVolatility: 0.06,
    },
  },
  {
    key: 'glasses-cloth',
    supplier: {
      supplier: '寧波繊維雑貨',
      channel: 'alibaba',
      source: '1688',
      title: '眼镜布 超细纤维 メガネ拭き クロス 15×15cm 10枚セット',
      modelNumber: 'GC-1515',
      currency: 'CNY',
      unitPrice: 4.1,
      moq: 50,
      domesticShippingJpy: 15,
      intlShippingPerUnitJpy: 45,
      dutyRate: 0.05,
      inspectionFeeJpy: 10,
      otherImportFeeJpy: 15,
      leadTimeDays: 15,
      supplierRating: 4.7,
      supplierOrderCount: 2600,
      attributes: A({
        sizeCm: { length: 15, width: 15, height: 1 },
        weightG: 60,
        color: 'アソート',
        material: 'マイクロファイバー',
        setCount: 10,
        spec: '15×15cm 10枚',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE004',
      title: 'メガネ拭き クロス マイクロファイバー 15×15cm 10枚セット アソート',
      brand: 'CLEARLY',
      modelNumber: 'GC-1515',
      category: 'ドラッグストア',
      priceJpy: 980,
      bsr: 15800,
      reviewCount: 22,
      rating: 4.4,
      sellerCount: 2,
      isAmazonSelling: false,
      monthlySold: null,
      imageCount: 3,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 15, width: 15, height: 1 },
        weightG: 62,
        color: 'アソート',
        material: 'マイクロファイバー',
        setCount: 10,
        spec: '10枚セット',
      }),
      imageBitFlips: 4,
      priceVolatility: 0.04,
    },
  },
  {
    key: 'camp-lantern',
    supplier: {
      supplier: '寧波アウトドア製造',
      channel: 'alibaba',
      source: 'alibaba',
      title: '折叠露营灯 折りたたみ LEDランタン USB充電 300ルーメン 防水IPX4',
      modelNumber: 'CL-300',
      currency: 'CNY',
      unitPrice: 23.0,
      moq: 10,
      domesticShippingJpy: 40,
      intlShippingPerUnitJpy: 210,
      dutyRate: 0.03,
      inspectionFeeJpy: 40,
      otherImportFeeJpy: 35,
      leadTimeDays: 20,
      supplierRating: 4.5,
      supplierOrderCount: 900,
      attributes: A({
        sizeCm: { length: 12, width: 8, height: 8 },
        weightG: 280,
        color: 'ブラック',
        material: 'ABS',
        setCount: 1,
        spec: 'USB充電 300ルーメン 防水IPX4',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE005',
      title: 'LEDランタン 折りたたみ USB充電式 300ルーメン 防水 キャンプ ブラック',
      brand: 'OUTFIELD',
      modelNumber: 'CL-300',
      category: 'スポーツ＆アウトドア',
      priceJpy: 3480,
      bsr: 6900,
      reviewCount: 58,
      rating: 4.1,
      sellerCount: 8,
      isAmazonSelling: false,
      monthlySold: 95,
      imageCount: 6,
      hasVideo: true,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 12, width: 8, height: 8 },
        weightG: 290,
        color: 'ブラック',
        material: 'ABS',
        setCount: 1,
        spec: 'USB充電 300ルーメン IPX4',
      }),
      imageBitFlips: 3,
      priceVolatility: 0.12,
    },
  },
  {
    key: 'knife-sharpener',
    supplier: {
      supplier: '陽江刃物工場',
      channel: 'alibaba',
      source: '1688',
      title: '磨刀器 包丁研ぎ器 3段式 セラミック 吸盤付き ホワイト',
      modelNumber: 'KS-3W',
      currency: 'CNY',
      unitPrice: 8.4,
      moq: 20,
      domesticShippingJpy: 28,
      intlShippingPerUnitJpy: 130,
      dutyRate: 0.03,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 25,
      leadTimeDays: 17,
      supplierRating: 4.4,
      supplierOrderCount: 1200,
      attributes: A({
        sizeCm: { length: 20, width: 6, height: 6 },
        weightG: 210,
        color: 'ホワイト',
        material: 'セラミック・ABS',
        setCount: 1,
        spec: '3段式 吸盤付き',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE006',
      title: '包丁研ぎ器 3段階 シャープナー 吸盤付き セラミック ホワイト',
      brand: 'TOGIYA',
      modelNumber: 'KS-3W',
      category: 'ホーム＆キッチン',
      priceJpy: 1980,
      bsr: 11200,
      reviewCount: 34,
      rating: 3.9,
      sellerCount: 4,
      isAmazonSelling: false,
      monthlySold: null,
      imageCount: 4,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 20, width: 6, height: 6 },
        weightG: 205,
        color: 'ホワイト',
        material: 'セラミック',
        setCount: 1,
        spec: '3段階 吸盤',
      }),
      imageBitFlips: 5,
      priceVolatility: 0.07,
    },
  },
  {
    key: 'compress-bag',
    supplier: {
      supplier: '青島包装材工場',
      channel: 'alibaba',
      source: '1688',
      title: '真空压缩袋 衣類圧縮袋 6枚組 手押しポンプ付き 70×50cm',
      modelNumber: 'CB-6P',
      currency: 'CNY',
      unitPrice: 13.2,
      moq: 20,
      domesticShippingJpy: 30,
      intlShippingPerUnitJpy: 140,
      dutyRate: 0.05,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 25,
      leadTimeDays: 16,
      supplierRating: 4.6,
      supplierOrderCount: 2100,
      attributes: A({
        sizeCm: { length: 26, width: 20, height: 5 },
        weightG: 420,
        color: 'クリア',
        material: 'PA/PE',
        setCount: 6,
        spec: '70×50cm 手押しポンプ付き',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE007',
      title: '衣類圧縮袋 6枚セット ポンプ付き 70×50cm 掃除機不要 収納',
      brand: 'SUKKIRI',
      modelNumber: 'CB-6P',
      category: 'ホーム＆キッチン',
      priceJpy: 2680,
      bsr: 5400,
      reviewCount: 96,
      rating: 4.0,
      sellerCount: 9,
      isAmazonSelling: false,
      monthlySold: 180,
      imageCount: 7,
      hasVideo: false,
      hasAplus: true,
      attributes: A({
        sizeCm: { length: 26, width: 20, height: 5 },
        weightG: 430,
        color: 'クリア',
        material: 'PA/PE',
        setCount: 6,
        spec: '70×50cm ポンプ付き',
      }),
      imageBitFlips: 4,
      priceVolatility: 0.09,
    },
  },
  {
    key: 'bike-light',
    supplier: {
      supplier: '深圳自転車部品',
      channel: 'alibaba',
      source: 'aliexpress',
      title: '自行车尾灯 自転車 LED テールライト USB充電 5モード 防水',
      modelNumber: 'BL-5R',
      currency: 'USD',
      unitPrice: 2.4,
      moq: 10,
      domesticShippingJpy: 20,
      intlShippingPerUnitJpy: 90,
      dutyRate: 0.03,
      inspectionFeeJpy: 15,
      otherImportFeeJpy: 20,
      leadTimeDays: 21,
      supplierRating: 4.3,
      supplierOrderCount: 640,
      attributes: A({
        sizeCm: { length: 7, width: 3, height: 3 },
        weightG: 45,
        color: 'レッド',
        material: 'ABS',
        setCount: 1,
        spec: 'USB充電 5モード 防水',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE008',
      title: '自転車 テールライト LED USB充電式 5モード 防水 リアライト',
      brand: 'RIDEON',
      modelNumber: 'BL-5R',
      category: 'スポーツ＆アウトドア',
      priceJpy: 1580,
      bsr: 9800,
      reviewCount: 47,
      rating: 4.2,
      sellerCount: 14,
      isAmazonSelling: false,
      monthlySold: null,
      imageCount: 5,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 7, width: 3, height: 3 },
        weightG: 48,
        color: 'レッド',
        material: 'ABS',
        setCount: 1,
        spec: 'USB充電 5モード 防水',
      }),
      imageBitFlips: 3,
      priceVolatility: 0.1,
    },
  },
  {
    key: 'ice-tray',
    supplier: {
      supplier: '台州家庭用品',
      channel: 'alibaba',
      source: '1688',
      title: '硅胶冰格 製氷皿 フタ付き 24個取り シリコン 2個セット',
      modelNumber: 'IT-24',
      currency: 'CNY',
      unitPrice: 7.6,
      moq: 20,
      domesticShippingJpy: 25,
      intlShippingPerUnitJpy: 105,
      dutyRate: 0.03,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 20,
      leadTimeDays: 15,
      supplierRating: 4.7,
      supplierOrderCount: 3100,
      attributes: A({
        sizeCm: { length: 22, width: 11, height: 4 },
        weightG: 240,
        color: 'グレー',
        material: 'シリコン',
        setCount: 2,
        spec: 'フタ付き 24個取り',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE009',
      title: '製氷皿 シリコン フタ付き 24個取り 2個セット 冷凍 グレー',
      brand: 'KOORI',
      modelNumber: 'IT-24',
      category: 'ホーム＆キッチン',
      priceJpy: 1680,
      bsr: 13400,
      reviewCount: 19,
      rating: 4.5,
      sellerCount: 2,
      isAmazonSelling: false,
      monthlySold: null,
      imageCount: 3,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 22, width: 11, height: 4 },
        weightG: 245,
        color: 'グレー',
        material: 'シリコン',
        setCount: 2,
        spec: 'フタ付き 24個取り',
      }),
      imageBitFlips: 2,
      priceVolatility: 0.03,
    },
  },
  {
    key: 'shade-net',
    supplier: {
      supplier: '山東農資工場',
      channel: 'alibaba',
      source: '1688',
      title: '遮阳网 園芸用 遮光ネット 遮光率75% 2m×3m ブラック',
      modelNumber: 'SN-2030',
      currency: 'CNY',
      unitPrice: 15.5,
      moq: 10,
      domesticShippingJpy: 45,
      intlShippingPerUnitJpy: 260,
      dutyRate: 0.05,
      inspectionFeeJpy: 25,
      otherImportFeeJpy: 30,
      leadTimeDays: 19,
      supplierRating: 4.2,
      supplierOrderCount: 420,
      attributes: A({
        sizeCm: { length: 40, width: 18, height: 8 },
        weightG: 900,
        color: 'ブラック',
        material: 'HDPE',
        setCount: 1,
        spec: '遮光率75% 2m×3m',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE010',
      title: '遮光ネット 2m×3m 遮光率75% 園芸 農業 日よけ ブラック',
      brand: 'NIWAKURA',
      modelNumber: 'SN-2030',
      category: 'DIY・工具・ガーデン',
      priceJpy: 3280,
      bsr: 24000,
      reviewCount: 12,
      rating: 4.0,
      sellerCount: 3,
      isAmazonSelling: false,
      monthlySold: null,
      imageCount: 2,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 40, width: 18, height: 8 },
        weightG: 920,
        color: 'ブラック',
        material: 'HDPE',
        setCount: 1,
        spec: '遮光率75% 2m×3m',
      }),
      imageBitFlips: 6,
      priceVolatility: 0.05,
    },
  },
  {
    key: 'nail-brush',
    supplier: {
      supplier: '広州美容雑貨',
      channel: 'alibaba',
      source: '1688',
      title: '美甲除尘刷 ネイル ダストブラシ 5本セット 天然毛 ピンク',
      modelNumber: 'NB-5P',
      currency: 'CNY',
      unitPrice: 5.4,
      moq: 30,
      domesticShippingJpy: 18,
      intlShippingPerUnitJpy: 55,
      dutyRate: 0.03,
      inspectionFeeJpy: 12,
      otherImportFeeJpy: 15,
      leadTimeDays: 15,
      supplierRating: 4.5,
      supplierOrderCount: 1500,
      attributes: A({
        sizeCm: { length: 16, width: 6, height: 2 },
        weightG: 55,
        color: 'ピンク',
        material: '天然毛・木',
        setCount: 5,
        spec: '5本セット',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE011',
      title: 'ネイルブラシ ダストブラシ 5本セット ジェルネイル 掃除 ピンク',
      brand: 'NAILDAYS',
      modelNumber: 'NB-5P',
      category: 'ビューティー',
      priceJpy: 1180,
      bsr: 18900,
      reviewCount: 15,
      rating: 4.3,
      sellerCount: 3,
      isAmazonSelling: false,
      monthlySold: null,
      imageCount: 3,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 16, width: 6, height: 2 },
        weightG: 58,
        color: 'ピンク',
        material: '天然毛',
        setCount: 5,
        spec: '5本セット',
      }),
      imageBitFlips: 4,
      priceVolatility: 0.06,
    },
  },

  // ---------- 競合が多すぎて C になる帯 ----------
  {
    key: 'usbc-cable',
    supplier: {
      supplier: '深圳配線材工場',
      channel: 'alibaba',
      source: 'alibaba',
      title: 'USB-C 数据线 USB-Cケーブル 1m 3本セット ナイロン編み 60W',
      modelNumber: 'UC-1M3',
      currency: 'CNY',
      unitPrice: 10.2,
      moq: 20,
      domesticShippingJpy: 25,
      intlShippingPerUnitJpy: 100,
      dutyRate: 0.03,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 25,
      leadTimeDays: 18,
      supplierRating: 4.6,
      supplierOrderCount: 8800,
      attributes: A({
        sizeCm: { length: 14, width: 10, height: 4 },
        weightG: 190,
        color: 'ブラック',
        material: 'ナイロン',
        setCount: 3,
        spec: '1m 60W 3本',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE012',
      title: 'USB-Cケーブル 1m 3本セット 60W急速充電 ナイロン編み ブラック',
      brand: 'CHARGEFIT',
      modelNumber: 'UC-1M3',
      category: '家電＆カメラ',
      priceJpy: 1680,
      bsr: 1900,
      reviewCount: 640,
      rating: 4.2,
      sellerCount: 28,
      isAmazonSelling: false,
      monthlySold: 720,
      imageCount: 7,
      hasVideo: true,
      hasAplus: true,
      attributes: A({
        sizeCm: { length: 14, width: 10, height: 4 },
        weightG: 195,
        color: 'ブラック',
        material: 'ナイロン',
        setCount: 3,
        spec: '1m 60W 3本',
      }),
      imageBitFlips: 3,
      priceVolatility: 0.14,
    },
  },
  {
    key: 'cooler-bag',
    supplier: {
      supplier: '杭州バッグ製造',
      channel: 'alibaba',
      source: '1688',
      title: '保温袋 保冷バッグ 折りたたみ 15L アルミ内張り グレー',
      modelNumber: 'CB-15L',
      currency: 'CNY',
      unitPrice: 14.8,
      moq: 20,
      domesticShippingJpy: 35,
      intlShippingPerUnitJpy: 180,
      dutyRate: 0.05,
      inspectionFeeJpy: 25,
      otherImportFeeJpy: 30,
      leadTimeDays: 17,
      supplierRating: 4.4,
      supplierOrderCount: 1100,
      attributes: A({
        sizeCm: { length: 30, width: 22, height: 10 },
        weightG: 380,
        color: 'グレー',
        material: 'ポリエステル・アルミ',
        capacity: '15L',
        setCount: 1,
        spec: '折りたたみ 15L',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE013',
      title: '保冷バッグ 折りたたみ 15L アルミ内張り クーラーバッグ グレー',
      brand: 'HIYAHIYA',
      modelNumber: 'CB-15L',
      category: 'ホーム＆キッチン',
      priceJpy: 2280,
      bsr: 7200,
      reviewCount: 210,
      rating: 4.1,
      sellerCount: 19,
      isAmazonSelling: false,
      monthlySold: 150,
      imageCount: 6,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 30, width: 22, height: 10 },
        weightG: 390,
        color: 'グレー',
        material: 'ポリエステル',
        capacity: '15L',
        setCount: 1,
        spec: '折りたたみ 15L',
      }),
      imageBitFlips: 5,
      priceVolatility: 0.11,
    },
  },

  // ---------- 輸入規制で D になる帯（安全装置の実動作確認）----------
  {
    key: 'power-bank',
    supplier: {
      supplier: '深圳電池工場',
      channel: 'alibaba',
      source: 'alibaba',
      title: '移动电源 モバイルバッテリー 10000mAh PD20W 小型 ブラック',
      modelNumber: 'PB-10K',
      currency: 'CNY',
      unitPrice: 32.0,
      moq: 10,
      domesticShippingJpy: 40,
      intlShippingPerUnitJpy: 320,
      dutyRate: 0.03,
      inspectionFeeJpy: 45,
      otherImportFeeJpy: 40,
      leadTimeDays: 22,
      supplierRating: 4.7,
      supplierOrderCount: 5600,
      attributes: A({
        sizeCm: { length: 10, width: 6, height: 2.5 },
        weightG: 210,
        color: 'ブラック',
        material: 'ABS',
        setCount: 1,
        spec: '10000mAh PD20W',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE014',
      title: 'モバイルバッテリー 10000mAh PD20W 小型 軽量 急速充電 ブラック',
      brand: 'POWERGO',
      modelNumber: 'PB-10K',
      category: '家電＆カメラ',
      priceJpy: 3480,
      bsr: 1200,
      reviewCount: 380,
      rating: 4.3,
      sellerCount: 11,
      isAmazonSelling: false,
      monthlySold: 900,
      imageCount: 7,
      hasVideo: true,
      hasAplus: true,
      attributes: A({
        sizeCm: { length: 10, width: 6, height: 2.5 },
        weightG: 215,
        color: 'ブラック',
        material: 'ABS',
        setCount: 1,
        spec: '10000mAh PD20W',
      }),
      imageBitFlips: 2,
      priceVolatility: 0.13,
    },
  },
  {
    key: 'earbuds',
    supplier: {
      supplier: '深圳音響工場',
      channel: 'alibaba',
      source: 'alibaba',
      title: '无线耳机 ワイヤレスイヤホン Bluetooth5.3 ノイズキャンセリング 白',
      modelNumber: 'WE-53',
      currency: 'CNY',
      unitPrice: 41.0,
      moq: 10,
      domesticShippingJpy: 35,
      intlShippingPerUnitJpy: 260,
      dutyRate: 0.03,
      inspectionFeeJpy: 45,
      otherImportFeeJpy: 40,
      leadTimeDays: 20,
      supplierRating: 4.5,
      supplierOrderCount: 3300,
      attributes: A({
        sizeCm: { length: 7, width: 5, height: 3 },
        weightG: 60,
        color: 'ホワイト',
        material: 'ABS',
        setCount: 1,
        spec: 'Bluetooth5.3 ノイズキャンセリング',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE015',
      title: 'ワイヤレスイヤホン Bluetooth5.3 ノイズキャンセリング 軽量 ホワイト',
      brand: 'SOUNDLY',
      modelNumber: 'WE-53',
      category: '家電＆カメラ',
      priceJpy: 4980,
      bsr: 800,
      reviewCount: 1200,
      rating: 4.1,
      sellerCount: 24,
      isAmazonSelling: true,
      monthlySold: 1400,
      imageCount: 8,
      hasVideo: true,
      hasAplus: true,
      attributes: A({
        sizeCm: { length: 7, width: 5, height: 3 },
        weightG: 62,
        color: 'ホワイト',
        material: 'ABS',
        setCount: 1,
        spec: 'Bluetooth5.3 ノイキャン',
      }),
      imageBitFlips: 3,
      priceVolatility: 0.16,
    },
  },
  {
    key: 'dog-treat',
    supplier: {
      supplier: '青島食品加工',
      channel: 'alibaba',
      source: '1688',
      title: '宠物零食 犬用 ささみジャーキー 500g 業務用 犬 おやつ',
      modelNumber: 'DT-500',
      currency: 'CNY',
      unitPrice: 18.0,
      moq: 20,
      domesticShippingJpy: 30,
      intlShippingPerUnitJpy: 190,
      dutyRate: 0.08,
      inspectionFeeJpy: 30,
      otherImportFeeJpy: 60,
      leadTimeDays: 25,
      supplierRating: 4.1,
      supplierOrderCount: 300,
      attributes: A({
        sizeCm: { length: 25, width: 18, height: 6 },
        weightG: 520,
        color: null,
        material: '鶏ささみ',
        capacity: '500g',
        setCount: 1,
        spec: '業務用 500g',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE016',
      title: '犬用 おやつ ささみ ジャーキー 500g 大容量 無添加',
      brand: 'WANWANKITCHEN',
      modelNumber: 'DT-500',
      category: 'ペット用品',
      priceJpy: 2480,
      bsr: 5600,
      reviewCount: 88,
      rating: 4.4,
      sellerCount: 6,
      isAmazonSelling: false,
      monthlySold: 160,
      imageCount: 5,
      hasVideo: false,
      hasAplus: false,
      isFood: true,
      attributes: A({
        sizeCm: { length: 25, width: 18, height: 6 },
        weightG: 530,
        material: '鶏ささみ',
        capacity: '500g',
        setCount: 1,
        spec: '500g',
      }),
      imageBitFlips: 7,
      priceVolatility: 0.07,
    },
  },

  // ---------- Amazonに無い（照合不成立）----------
  {
    key: 'no-amazon-1',
    supplier: {
      supplier: '汕頭雑貨工場',
      channel: 'alibaba',
      source: '1688',
      title: '创意收纳盒 デスク 小物入れ 回転式 5段 パステル',
      modelNumber: 'RS-5P',
      currency: 'CNY',
      unitPrice: 12.4,
      moq: 30,
      domesticShippingJpy: 30,
      intlShippingPerUnitJpy: 160,
      dutyRate: 0.05,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 25,
      leadTimeDays: 18,
      supplierRating: 4.0,
      supplierOrderCount: 210,
      attributes: A({
        sizeCm: { length: 18, width: 18, height: 24 },
        weightG: 620,
        color: 'パステル',
        material: 'PP',
        setCount: 1,
        spec: '回転式 5段',
      }),
    },
    amazon: null,
  },
  {
    key: 'no-amazon-2',
    supplier: {
      supplier: '義烏文具商社',
      channel: 'alibaba',
      source: '1688',
      title: '和纸胶带切割器 マスキングテープカッター 木製 3連',
      modelNumber: 'MT-3W',
      currency: 'CNY',
      unitPrice: 9.0,
      moq: 30,
      domesticShippingJpy: 22,
      intlShippingPerUnitJpy: 120,
      dutyRate: 0.03,
      inspectionFeeJpy: 15,
      otherImportFeeJpy: 20,
      leadTimeDays: 16,
      supplierRating: 4.2,
      supplierOrderCount: 180,
      attributes: A({
        sizeCm: { length: 20, width: 8, height: 6 },
        weightG: 280,
        color: 'ナチュラル',
        material: '木',
        setCount: 1,
        spec: '3連',
      }),
    },
    amazon: null,
  },

  // ---------- 利益が出ない（Dになる）----------
  {
    key: 'thin-margin',
    supplier: {
      supplier: '寧波日用品B',
      channel: 'alibaba',
      source: '1688',
      title: '洗碗海绵 食器用スポンジ 10個入 抗菌 三層構造',
      modelNumber: 'SP-10',
      currency: 'CNY',
      unitPrice: 11.0,
      moq: 50,
      domesticShippingJpy: 25,
      intlShippingPerUnitJpy: 150,
      dutyRate: 0.05,
      inspectionFeeJpy: 20,
      otherImportFeeJpy: 25,
      leadTimeDays: 16,
      supplierRating: 4.3,
      supplierOrderCount: 700,
      attributes: A({
        sizeCm: { length: 24, width: 14, height: 10 },
        weightG: 300,
        color: 'アソート',
        material: 'ウレタン',
        setCount: 10,
        spec: '抗菌 三層構造 10個',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE017',
      title: '食器用スポンジ 10個セット 抗菌 三層構造 キッチン アソート',
      brand: 'ARAERU',
      modelNumber: 'SP-10',
      category: 'ホーム＆キッチン',
      priceJpy: 880,
      bsr: 3100,
      reviewCount: 320,
      rating: 4.2,
      sellerCount: 16,
      isAmazonSelling: true,
      monthlySold: 450,
      imageCount: 5,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 24, width: 14, height: 10 },
        weightG: 310,
        color: 'アソート',
        material: 'ウレタン',
        setCount: 10,
        spec: '抗菌 三層 10個',
      }),
      imageBitFlips: 4,
      priceVolatility: 0.06,
    },
  },

  // ---------- OEM候補になる帯（売れているが不満が多い）----------
  {
    key: 'oem-hanger',
    supplier: {
      supplier: '広東樹脂製品',
      channel: 'alibaba',
      source: '1688',
      title: '衣架 すべらないハンガー 30本セット PVCコーティング 肩幅42cm',
      modelNumber: 'HG-30',
      currency: 'CNY',
      unitPrice: 26.0,
      moq: 10,
      domesticShippingJpy: 45,
      intlShippingPerUnitJpy: 280,
      dutyRate: 0.05,
      inspectionFeeJpy: 30,
      otherImportFeeJpy: 35,
      leadTimeDays: 19,
      supplierRating: 4.5,
      supplierOrderCount: 1400,
      attributes: A({
        sizeCm: { length: 44, width: 24, height: 14 },
        weightG: 1800,
        color: 'ブラック',
        material: 'ABS・PVC',
        setCount: 30,
        spec: '肩幅42cm 30本',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE018',
      title: 'すべらないハンガー 30本セット 42cm 薄型 PVCコーティング ブラック',
      brand: 'HANGERLAB',
      modelNumber: 'HG-30',
      category: 'ホーム＆キッチン',
      priceJpy: 3980,
      bsr: 1500,
      reviewCount: 540,
      rating: 3.6,
      sellerCount: 7,
      isAmazonSelling: false,
      monthlySold: 380,
      imageCount: 6,
      hasVideo: false,
      hasAplus: false,
      attributes: A({
        sizeCm: { length: 44, width: 24, height: 14 },
        weightG: 1850,
        color: 'ブラック',
        material: 'ABS・PVC',
        setCount: 30,
        spec: '42cm 30本',
      }),
      imageBitFlips: 3,
      priceVolatility: 0.08,
    },
  },
  {
    key: 'oem-bottle',
    supplier: {
      supplier: '永康ボトル製造',
      channel: 'alibaba',
      source: 'alibaba',
      title: '保温杯 ステンレスボトル 500ml 真空断熱 直飲み マットブラック',
      modelNumber: 'SB-500',
      currency: 'CNY',
      unitPrice: 29.0,
      moq: 10,
      domesticShippingJpy: 35,
      intlShippingPerUnitJpy: 240,
      dutyRate: 0.03,
      inspectionFeeJpy: 35,
      otherImportFeeJpy: 35,
      leadTimeDays: 18,
      supplierRating: 4.8,
      supplierOrderCount: 4200,
      attributes: A({
        sizeCm: { length: 7, width: 7, height: 22 },
        weightG: 300,
        color: 'マットブラック',
        material: 'ステンレス',
        capacity: '500ml',
        setCount: 1,
        spec: '真空断熱 直飲み',
      }),
    },
    amazon: {
      asin: 'B0SAMPLE019',
      title: 'ステンレスボトル 500ml 真空断熱 直飲み マットブラック 水筒',
      brand: 'MIZUBE',
      modelNumber: 'SB-500',
      category: 'ホーム＆キッチン',
      priceJpy: 2980,
      bsr: 2200,
      reviewCount: 460,
      rating: 3.7,
      sellerCount: 9,
      isAmazonSelling: false,
      monthlySold: 300,
      imageCount: 7,
      hasVideo: false,
      hasAplus: true,
      attributes: A({
        sizeCm: { length: 7, width: 7, height: 22 },
        weightG: 305,
        color: 'マットブラック',
        material: 'ステンレス',
        capacity: '500ml',
        setCount: 1,
        spec: '真空断熱 直飲み',
      }),
      imageBitFlips: 2,
      priceVolatility: 0.09,
    },
  },
];
